package USDSL.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import USDSL.behavior.UseCase__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class actionFieldFactories {
  public static class NodeFactory_7906954222571510387 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      SNode useCaseNode = (SNode) enclosingNode;
      SPropertyOperations.assign(newNode, PROPS.actionNumber$PYb2, ((int) UseCase__BehaviorDescriptor.getNumberOfActionFields_id6QV9fzVDp7I.invoke(useCaseNode) + 1) + ".");

    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty actionNumber$PYb2 = MetaAdapterFactory.getProperty(0x810c97e7e104dadL, 0x97d97fc9c6808e25L, 0x6ae5bdeae41a19c6L, 0x6dbb24f8fba65a69L, "actionNumber");
  }
}
